### ISSUE TITLE
Fehler im Test auf Windows Systemen

### ISSUE THREAD

**Issue by myTrx** [SimonBas/ScrewBox#127]
In Datei ResourcesTest.java

Korrektur so:

    @Test
    void classPathElements_returnsElementsFromClassPath() {
        List<String> elements = Resources.classPathElements();
        assertThat(elements).isNotEmpty()
                .anyMatch(element -> element.contains(File.separator + "jackson-databind" + File.separator));
    }

**Comment by srcimon** [comment]
Hey @myTrx nice, danke! Das war nicht das einzige Problem mit Windows. Habe jetzt [v1.0.0-RC2](https://github.com/srcimon/screwbox/releases/tag/1.0.0-RC2) released.
